// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/petua/linking-talk/src/language-linkage/inter-language-linking/go-main.go:1:1
package main

// #cgo LDFLAGS: -L${SRCDIR}/libs -lcpplib -Wl,-rpath,${SRCDIR}/libs
// #include "cpplib.h"
import _ "unsafe"
import (
	"fmt"
	"math/rand"
)

func main() {
	arr := make([]int32, 15)
	for i := range arr {
		arr[i] = int32(rand.Int())
	}
	fmt.Print("Initial range: ")
	for _, el := range arr {
		fmt.Print(el, " ")
	}
	fmt.Println()

	( /*line :22:2*/_Cfunc_sort_range /*line :22:13*/)((* /*line :22:17*/_Ctype_int /*line :22:22*/)(&arr[0]), (* /*line :22:36*/_Ctype_int /*line :22:41*/)(&arr[len(arr)-1]))
	fmt.Print("Sorted range: ")
	for _, el := range arr {
		fmt.Print(el, " ")
	}
	fmt.Println()
}
